# Generated by Django 6.0.3 on 2026-03-25 21:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=150)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento_fatura', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('melhor_dia', models.IntegerField(choices=[(1, 'Dia1'), (2, 'Dia2'), (3, 'Dia3'), (4, 'Dia4'), (5, 'Dia5'), (6, 'Dia6'), (7, 'Dia7'), (8, 'Dia8'), (9, 'Dia9'), (10, 'Dia10'), (11, 'Dia11'), (12, 'Dia12'), (13, 'Dia13'), (14, 'Dia14'), (15, 'Dia15'), (16, 'Dia16'), (17, 'Dia17'), (18, 'Dia18'), (19, 'Dia19'), (20, 'Dia20'), (21, 'Dia21'), (22, 'Dia22'), (23, 'Dia23'), (24, 'Dia24'), (25, 'Dia25'), (26, 'Dia26'), (27, 'Dia27'), (28, 'Dia28'), (29, 'Dia29'), (30, 'Dia30')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('voucher', 'Voucher')], max_length=20)),
                ('cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.cartao')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
