# Generated by Django 6.0.3 on 2026-03-28 20:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=150)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento_fatura', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
                ('melhor_dia', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='TransacaoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('lazer', 'Lazer'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('compras', 'Compras'), ('assinaturas', 'Assinaturas'), ('contas', 'Contas'), ('outros', 'Outros')], max_length=30)),
                ('tipo_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao', 'Cartão'), ('voucher', 'Voucher')], max_length=20)),
                ('cartao', models.CharField(choices=[('nubank', 'Nubank'), ('itau', 'Itaú'), ('bradesco', 'Bradesco'), ('santander', 'Santander'), ('bb', 'Banco do Brasil'), ('caixa', 'Caixa Econômica Federal'), ('inter', 'Banco Inter'), ('c6', 'C6 Bank'), ('sicredi', 'Sicredi'), ('banrisul', 'Banrisul')], max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transações | Compras',
            },
        ),
        migrations.CreateModel(
            name='TransacaoRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transações | Recebimentos',
            },
        ),
    ]
