# Generated by Django 6.0.3 on 2026-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartao',
            options={'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterModelOptions(
            name='transacaocompra',
            options={'verbose_name_plural': 'Transações | Compras'},
        ),
        migrations.AlterField(
            model_name='cartao',
            name='melhor_dia',
            field=models.IntegerField(choices=[]),
        ),
    ]
