# Generated by Django 6.0.3 on 2026-03-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartao',
        ),
    ]
