# Generated by Django 6.0.3 on 2026-03-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome_completo',
        ),
    ]
